INSERT INTO
  DEPARTMENT
VALUES
  (1, 'HR', 'HUMAN RESOURCES');

INSERT INTO
  DEPARTMENT
VALUES
  (2, '9UP', '9UP DEPARTMENT');

INSERT INTO
  DEPARTMENT
VALUES
  (3, 'IT', 'INFORMATION TECHNOLOGY DEPARTMENT');

INSERT INTO
  DEPARTMENT
VALUES
  (4, 'SA', 'SALES DEPARTMENT');