server: 
  port: 8083
  

spring.datasource:
  url: jdbc:mysql://localhost:3306/org
  username: root
  password: Tong1203!
  driver-class-name: com.mysql.cj.jdbc.Driver
spring.jpa:
  properties.hibernate.dialect: org.hibernate.dialect.MySQL8Dialect
  hibernate.ddl-auto: none
  show-sql: true

# spring.datasource:
#   url: jdbc:mysql://localhost:3306/sys
#   username: root
#   password: 
#   driver-class-name: com.mysql.cj.jdbc.Driver
# spring.jpa:
#   properties.hibernate.dialect: org.hibernate.dialect.MySQL8Dialect
#   hibernate.ddl-auto: none
#   show-sql: true