DROP TABLE IF EXISTS BOOKS;

DROP TABLE IF EXISTS AUTHORS;

USE SYS;

CREATE TABLE AUTHORS (
  ID INTEGER PRIMARY KEY auto_increment,
  AUTHOR_NAME VARCHAR (30) NOT NULL,
  AUTHOR_NAT VARCHAR (2) NOT NULL
);