USE SYS;

CREATE TABLE BOOKS (
  ID INTEGER auto_increment NOT NULL,
  BOOK_NAME VARCHAR (20) NOT NULL,
  -- book_Author VARCHAR (20) NOT NULL,
  PUBLIC_DATE DATE NOT NULL,
  AUTHOR_ID INTEGER NOT NULL,
  CONSTRAINT PK_BOOKS PRIMARY KEY (ID),
  CONSTRAINT FK_BOOKS FOREIGN KEY (AUTHOR_ID) REFERENCES AUTHORS (ID)
);