Server: 
  port: 8091


service:
  appId: 4498d232c2565e705a0d01363d63abb5
  currentweather:
    baseUrl: http://api.openweathermap.org
    serviceVers: data/2.5
    serviceUrl: weather

rest:
  conn-mgr:
    connection:
      max-total: 20
      max-per-route: 40
    check:
      inactivity: 1000
  http-client:
    timeout:
      evictIdleConnection: 5
  http-request-factory:
    timeout:
      pool-connect: 10000
      server-connect: 10000
      server-read: 20000

spring:
  data:
   redis:
    database: 0
    host: localhost
    port: 6379
    password: 
    timeout: 60000
  
  datasource:
    url: jdbc:mysql://localhost:3306/sys
    username: root
    password: Tong1203!
    driver-class-name: com.mysql.cj.jdbc.Driver



