DELETE FROM
  BOOKS
WHERE
  ID IN (1, 2, 3, 4, 5);

INSERT INTO
  BOOKS (ID, BOOK_NAME, PUBLIC_DATE, AUTHOR_ID)
VALUES
  (1, "DEVELOPERROAD", '2022-11-02', 1);

INSERT INTO
  BOOKS (ID, BOOK_NAME, PUBLIC_DATE, AUTHOR_ID)
VALUES
  (2, "COOKGUIDE", '2022-10-31', 2);

INSERT INTO
  BOOKS (ID, BOOK_NAME, PUBLIC_DATE, AUTHOR_ID)
VALUES
  (3, "DRIVEGUIDE", '2022-10-31', 1);

INSERT INTO
  BOOKS (ID, BOOK_NAME, PUBLIC_DATE, AUTHOR_ID)
VALUES
  (4, "JAVAINTRODUCTION", '2022-10-31', 2);

INSERT INTO
  BOOKS (ID, BOOK_NAME, PUBLIC_DATE, AUTHOR_ID)
VALUES
  (5, "RUNTOWORLD", '2022-10-31', 2);

COMMIT;