DELETE FROM
  TUTORS
WHERE
  ID IN (1, 2, 3, 4, 5);

INSERT INTO
  TUTORS (ID, TUTOR_NAME, TUTOR_NAT)
VALUES
  (1, 'VINCENT', 'US');

INSERT INTO
  TUTORS (ID, TUTOR_NAME, TUTOR_NAT)
VALUES
  (2, 'CHRIS', 'CN');

COMMIT;