DELETE FROM
  COURSES
WHERE
  ID IN (1, 2, 3);

INSERT INTO
  COURSES (
    ID,
    COURSE_NAME,
    COURSE_FEE,
    START_DATE,
    TUTORS_ID
  )
VALUES
  (1, 'JAVACOURSE', 15000.00, '2022-9-10', 1);

INSERT INTO
  COURSES (
    ID,
    COURSE_NAME,
    COURSE_FEE,
    START_DATE,
    TUTORS_ID
  )
VALUES
  (2, 'PYTHONCOURSE', 20000.00, '2022-9-10', 1);

INSERT INTO
  COURSES (
    ID,
    COURSE_NAME,
    COURSE_FEE,
    START_DATE,
    TUTORS_ID
  )
VALUES
  (3, 'FULLSTACKCOURSE', 30000.00, '2022-9-15', 2);

COMMIT;